name: Android Mobile Automation with Maven
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  android-tests:
    runs-on: ubuntu-latest
 
    steps:
    # 1. Checkout o código do repositório
    - name: Checkout code
      uses: actions/checkout@v3
 
    # 2. Configurar o JDK (Java 21, conforme mencionado anteriormente)
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
 
    # 3. Instalar dependências do Maven
    - name: Install dependencies
      run: mvn install -DskipTests
 
    # 4. Criar e iniciar o emulador Android
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        target: google_apis
        channel: stable
 
    - name: Create and start emulator
      run: |
        avdmanager create avd -n test -k "system-images;android-33;google_apis;x86_64" --device "pixel"
        emulator -avd test -no-snapshot -no-audio -no-window &
        adb wait-for-device
        adb shell input keyevent 82 # Unlock screen
 
    # 5. Executar os testes
    - name: Run Tests
      run: mvn test

 
