name: Android Mobile Automation with Java 21
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  android-tests:
    runs-on: ubuntu-latest
 
    steps:
    # 1. Checkout o código do repositório
    - name: Checkout code
      uses: actions/checkout@v3
 
    # 2. Configurar o ambiente Java para Java 21
    - name: Set up Java 21
      uses: actions/setup-java@v3
      with:
        java-version: 21
        distribution: 'zulu'
 
    # 3. Configurar o Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 35
        target: google_apis
        channel: stable
 
    # 4. Instalar dependências do projeto (Gradle)
    - name: Install dependencies
      run: |
        ./gradlew dependencies
 
    # 5. Criar e iniciar o emulador Android
    - name: Create and start emulator
      run: |
        avdmanager create avd -n test -k "system-images;android-35;google_apis;x86_64" --device "pixel"
        emulator -avd test -no-snapshot -no-audio -no-window &
        adb wait-for-device
        adb shell input keyevent 82 # Unlock screen
 
    # 6. Verificar se o emulador está funcionando
    - name: Verify Emulator is Running
      run: adb devices
 
    # 7. Executar os testes de automação
    - name: Run Tests
      run: |
        ./gradlew clean test
 
    # 8. Fazer upload dos relatórios de teste (opcional)
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: app/build/reports/
