name: Run Appium JUnit Android Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 35
        build-tools: 35.0.0
        target: android-35
        ndk: false

    - name: Install Android Emulator Dependencies
      run: |
        sdkmanager "platform-tools" "emulator"
        sdkmanager "system-images;android-35;google_apis;x86_64"
        
    - name: Create Android Emulator
      run: |
        echo "no" | avdmanager create avd -n test -k "system-images;android-35;google_apis;x86_64" --device "pixel"
        
    - name: Start Android Emulator
      run: |
        nohup emulator -avd test -no-window -no-audio -gpu swiftshader_indirect &
        adb wait-for-device
        adb shell getprop sys.boot_completed

    - name: Wait for Emulator to Boot
      run: |
        boot_completed="0"
        timeout=300 # Maximum wait time (5 minutes)
        elapsed=0
        while [ "$boot_completed" != "1" ] && [ $elapsed -lt $timeout ]; do
          boot_completed=$(adb shell getprop sys.boot_completed | tr -d '\r')
          if [ "$boot_completed" != "1" ]; then
            sleep 5
            elapsed=$((elapsed + 5))
          fi
        done
        if [ "$boot_completed" != "1" ]; then
          echo "Emulator failed to boot within $timeout seconds"
          exit 1
        fi
        echo "Emulator is ready."

    - name: Verify Emulator is Running
      run: adb shell input keyevent 82

    - name: Start Appium Server
      run: |
        npm install -g appium
        nohup appium &

    - name: Run Tests
      run: |
        ./gradlew test

    - name: Stop Emulator
      if: always()
      run: adb -s emulator-5554 emu kill
