name: Run Android Emulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Android Dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y \
          libvirt-daemon-system \
          libvirt-clients \
          qemu-kvm \
          libgl1-mesa-dri \
          libgl1-mesa-dev \
          lib32z1 \
          libc6:i386 \
          libstdc++6:i386

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 35
        build-tools: 35.0.0
        target: android-35
        ndk: false

    - name: Install System Image
      run: sdkmanager "system-images;android-35;google_apis;x86_64"

    - name: Create AVD
      run: |
        echo "no" | avdmanager create avd -n test -k "system-images;android-35;google_apis;x86_64" --device "pixel"

    - name: Start Emulator
      run: |
        nohup emulator -avd test -no-snapshot -no-window -gpu swiftshader_indirect -no-audio -verbose &
        sleep 60
        adb wait-for-device
        adb shell getprop sys.boot_completed | grep -m 1 "1"

    - name: Capture Emulator Logs (Optional Debug Step)
      if: failure()
      run: adb logcat -d > emulator-log.txt

    - name: Verify Emulator is Running
      run: adb shell input keyevent 82

    - name: Run Tests with Gradle
      run: ./gradlew clean test

    - name: Stop Emulator
      if: always()
      run: adb -s emulator-5554 emu kill
