name: Run Android Emulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 35
        build-tools: 35.0.0
        target: android-35

    - name: Start Emulator
      uses: ReactiveCircus/android-emulator-runner@v2
      with:
        api-level: 35
        target: google_apis
        arch: x86_64
        profile: pixel
        emulator-options: "-no-window -no-audio"

    - name: Verify Emulator is Running
      run: adb shell input keyevent 82

    - name: Run Tests with Gradle
      run: ./gradlew clean test

    - name: Stop Emulator
      if: always()
      run: adb -s emulator-5554 emu kill
