name: Run Android Emulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Emulator Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libvirt-dev qemu-kvm

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 33
        build-tools: 33.0.3
        target: google_apis

    - name: Start Emulator
      uses: ReactiveCircus/android-emulator-runner@v2
      with:
        api-level: 33
        target: google_apis
        arch: x86_64
        profile: pixel
        emulator-options: -no-window -no-audio -gpu swiftshader_indirect -verbose
        disable-linux-hw-accel: true
        avd-name: test
        force-avd-creation: true
        emulator-boot-timeout: 900
        disable-animations: true
        ram-size: 2048M
        disk-size: 2G

    - name: Wait for Emulator to Boot
      run: adb wait-for-device

    - name: Verify Emulator is Running
      run: adb shell getprop sys.boot_completed | grep -m 1 "1"

    - name: Run Tests with Gradle
      run: ./gradlew clean test

    - name: Stop Emulator
      if: always()
      run: adb -s emulator-5554 emu kill
