name: Android Mobile Automation
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  android-tests:
    runs-on: ubuntu-latest
 
    steps:
    # 1. Checkout o código do repositório
    - name: Checkout code
      uses: actions/checkout@v3
 
    # 2. Configurar o ambiente Java e Android SDK
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'zulu'
 
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 35
        target: google_apis
        channel: stable
 
    # 3. Baixar e configurar dependências do projeto
    - name: Install dependencies
      run: |
        ./gradlew dependencies
 
    # 4. Criar e iniciar o emulador Android
    - name: Create and start emulator
      run: |
        avdmanager create avd -n test -k "system-images;android-33;google_apis
